version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/authentication/application:/var/www/authentication
      - ./services/gateway/application:/var/www/gateway
    depends_on:
      - php
      - app-authentication
    networks:
      - mynetwork

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./services/authentication/application:/var/www/authentication
      - ./services/gateway/application:/var/www/gateway
    environment:
      - PHP_VERSION=8.2
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/users.acl:/data/users.acl
    command: redis-server --requirepass secret --aclfile /data/users.acl
    networks:
      - mynetwork

  redis_ui:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - mynetwork

# microservices setup

  gateway-workspace:
    build:
      context: ./services/gateway/workspace
      dockerfile: Dockerfile
    container_name: gateway-workspace
    volumes:
      - ./services/gateway/application:/var/www/gateway
    working_dir: /var/www/gateway
    depends_on:
      - php
    command: tail -f /dev/null
    networks:
      - mynetwork

  app-gateway:
    build:
      context: ./services/gateway/application
      dockerfile: Dockerfile
    container_name: app-gateway
    ports:
      - "8080:80"
    volumes:
      - ./services/gateway/application:/var/www/gateway
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - redis
      - authentication-nginx
    command: >
      sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"
    networks:
      - mynetwork

  authentication-workspace:
    build:
      context: ./services/authentication/workspace
      dockerfile: Dockerfile
    container_name: authentication-workspace
    volumes:
      - ./services/authentication/application:/var/www/authentication
    working_dir: /var/www/authentication
    depends_on:
      - php
    command: tail -f /dev/null
    networks:
      - mynetwork

  app-authentication:
    build:
      context: ./services/authentication/application
      dockerfile: Dockerfile
    container_name: app-authentication
    volumes:
      - ./services/authentication/application:/var/www/authentication
    working_dir: /var/www/authentication
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - redis
    command: >
      sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"
    networks:
      - mynetwork

  authentication-nginx:
    image: nginx:latest
    container_name: authentication-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/auth.conf:/etc/nginx/conf.d/default.conf
      - ./services/authentication/application:/var/www/authentication
    depends_on:
      - app-authentication
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
