version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-authentication

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_VERSION=8.2

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis_ui:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis

  app-authentication:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    container_name: app-authentication
    volumes:
    - ./services/authentication:/var/www/authentication
    working_dir: /var/www/authentication
    environment:
      - APP_ENV=local
      - DB_HOST=mysql_db
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

